global:
  scrape_interval: 15s     # Frecuencia de muestreo (Nyquist-Shannon compliant para eventos >30s)
  evaluation_interval: 15s

# --- SECCIÓN NUEVA ---
rule_files:
  - "alerts.yml"
# ---------------------

scrape_configs:
  - job_name: 'life-calendar-service'
    metrics_path: '/metrics'
    scheme: 'https'        # Render fuerza TLS, es mandatorio
    static_configs:
      # IMPORTANTE: Reemplaza este target con tu URL de producción real que ya desplegaste
      - targets: ['life-calendar-cfo3.onrender.com'] 
        labels:
          environment: 'production'
          service: 'life-calendar'
